FROM node:24-alpine

# Устанавливаем pnpm глобально в образ
RUN npm config set registry https://registry.npmmirror.com
RUN npm install -g pnpm@10.26.2

# Настраиваем переменные для корректной работы путей pnpm
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /workspace