name: go-with-me-production
services:
    - name: web
      github:
          branch: main
          deploy_on_push: false
      dockerfile_path: Dockerfile
      http_port: 3000
      instance_count: 1
      instance_size_slug: basic-xs
      routes:
          - path: /
      envs:
          - key: NODE_ENV
            value: production
