export const eventCategory = [
    "Music & Concerts",
    "Sport & Fitness",
    "Arts & Theatre",
    "Science & Engineering",
    "Food & Drink",
    "Networking & Social",
    "Technology & Innovation",
    "Family & Education",
    "Health & Wellnes",
    "Charity & Causes",
    "Travel & Outdoor",
    "Cultural & Religious",
    "Fashion & Beauty",
    "Hobbies & Special interest",
];

export const eventTypes = [
    "Party",
    "Gathering",
    "Meetup",
    "Conference",
    "Sport",
    "Workshop",
    "Seminar",
    "Concert",
    "Festival",
    "Exhibition",
    "Networking",
    "Trade Show",
    "Class/Course",
    "Lecture",
    "Fundraiser",
    "Gala",
    "Retreat",
    "Tour",
    "Competition",
    "Hackathon",
    "Fair",
    "Community Service/Volunteer Event",
    "Open House",
    "Theater/Play",
    "Dance Event",
];
