import type { Metadata } from 'next'
import Link from 'next/link'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <menu>
        <ul>
          <li><Link href="/events/1">Event No 1</Link></li>
        </ul>
      </menu>
      {children}
      </body>
    </html>
  )
}
