// export const eventCategory = [
//     "Music & Concerts",
//     "Sport & Fitness",
//     "Arts & Theatre",
//     "Science & Engineering",
//     "Food & Drink",
//     "Networking & Social",
//     "Technology & Innovation",
//     "Family & Education",
//     "Health & Wellnes",
//     "Charity & Causes",
//     "Travel & Outdoor",
//     "Cultural & Religious",
//     "Fashion & Beauty",
//     "Hobbies & Special interest",
// ];

export const categoriesList = [
    'Музыка и концерты',
    'Спорт и фитнес',
    'Искусство и театр',
    'Наука и инженерия',
    'Еда и напитки',
    'Нетворкинг и связи',
    'Технологии и инновации',
    'Семья и образование',
    'Здоровье и самочувствие',
    'Благотворительность и помощь',
    'Путешествие и отдых',
    'Культура и религия',
    'Мода и красота',
    'Хобби и увлечения',
];

export const interestsList = [
    'Вечеринка',
    'Собрание',
    'Встреча',
    'Конференция',
    'Спорт',
    'Мастер-класс',
    'Семинар',
    'Концерт',
    'Фестиваль',
    'Выставка',
    'Нетворкинг',
    'Торговая выставка',
    'Класс/Курс',
    'Лекция',
    'Благотворительное мероприятие',
    'Гала-вечер',
    'Ретрит',
    'Тур',
    'Соревнование',
    'Хакатон',
    'Ярмарка',
    'Волонтёрское мероприятие',
    'День открытых дверей',
    'Театр/Спектакль',
    'Танцевальное событие',
];

// export const eventTypes = [
//     "Party",
//     "Gathering",
//     "Meetup",
//     "Conference",
//     "Sport",
//     "Workshop",
//     "Seminar",
//     "Concert",
//     "Festival",
//     "Exhibition",
//     "Networking",
//     "Trade Show",
//     "Class/Course",
//     "Lecture",
//     "Fundraiser",
//     "Gala",
//     "Retreat",
//     "Tour",
//     "Competition",
//     "Hackathon",
//     "Fair",
//     "Community Service/Volunteer Event",
//     "Open House",
//     "Theater/Play",
//     "Dance Event",
// ];
